# Generated by Django 4.1.5 on 2023-10-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_name', models.CharField(max_length=255)),
                ('structure_type', models.CharField(choices=[('astrahus', 'Astrahus'), ('fortizar', 'Fortizar'), ('keepstar', 'Keepstar'), ('raitaru', 'Raitaru'), ('azbel', 'Azbel'), ('sotiyo', 'Sotiyo'), ('athanor', 'Athanor'), ('tatara', 'Tatara')], max_length=255)),
                ('structure_type_id', models.BigIntegerField()),
                ('system', models.CharField(max_length=255)),
                ('corporation_name', models.CharField(max_length=255)),
                ('corporation_id', models.BigIntegerField()),
                ('alliance_name', models.CharField(max_length=255)),
                ('alliance_id', models.BigIntegerField()),
                ('related_alliance_name', models.CharField(blank=True, max_length=255, null=True)),
                ('related_alliance_id', models.BigIntegerField(blank=True, null=True)),
                ('timer', models.CharField(max_length=5)),
                ('fitting', models.TextField()),
            ],
        ),
    ]
