# Generated by Django 4.1.5 on 2023-10-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0002_structure_constellation_structure_constellation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureIntel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_name', models.CharField(max_length=255)),
                ('structure_type', models.CharField(choices=[('astrahus', 'Astrahus'), ('fortizar', 'Fortizar'), ('keepstar', 'Keepstar'), ('raitaru', 'Raitaru'), ('azbel', 'Azbel'), ('sotiyo', 'Sotiyo'), ('athanor', 'Athanor'), ('tatara', 'Tatara')], max_length=255)),
                ('structure_type_id', models.BigIntegerField()),
                ('system', models.CharField(max_length=255)),
                ('system_id', models.BigIntegerField(blank=True, null=True)),
                ('constellation', models.CharField(blank=True, max_length=255, null=True)),
                ('constellation_id', models.BigIntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('region_id', models.BigIntegerField(blank=True, null=True)),
                ('corporation_name', models.CharField(max_length=255)),
                ('corporation_id', models.BigIntegerField()),
                ('alliance_name', models.CharField(max_length=255)),
                ('alliance_id', models.BigIntegerField()),
                ('related_alliance_name', models.CharField(blank=True, max_length=255, null=True)),
                ('related_alliance_id', models.BigIntegerField(blank=True, null=True)),
                ('timer', models.CharField(max_length=5)),
                ('fitting', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_character_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StructureIntelCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('constellation', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('alliance_name', models.CharField(blank=True, max_length=255, null=True)),
                ('related_alliance_name', models.CharField(blank=True, max_length=255, null=True)),
                ('price_per_structure', models.IntegerField(default=0)),
                ('structures', models.ManyToManyField(blank=True, to='intel.structureintel')),
            ],
        ),
        migrations.DeleteModel(
            name='Structure',
        ),
    ]
