# Generated by Django 4.1.5 on 2023-10-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0003_structureintel_structureintelcampaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structureintelcampaign',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('complete', 'Complete')], default='active', max_length=255),
        ),
    ]
