# Generated by Django 4.1.5 on 2023-10-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0004_structureintelcampaign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structureintel',
            name='alliance_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='structureintel',
            name='alliance_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
