# Generated by Django 4.1.5 on 2023-10-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0007_structureintel_created_by_character_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='structureintel',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
