# Generated by Django 4.1.5 on 2023-10-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0008_structureintel_verified'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='structureintel',
            unique_together={('system', 'structure_name')},
        ),
    ]
