# Generated by Django 4.1.5 on 2023-04-22 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EveCourierEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporation_id', models.IntegerField(unique=True)),
                ('ceo_id', models.BigIntegerField(blank=True)),
                ('corporation_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EveCourierPilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_character_id', models.BigIntegerField()),
                ('courier_character_name', models.CharField(max_length=255)),
                ('character_id', models.BigIntegerField(blank=True, null=True)),
                ('character_name', models.CharField(blank=True, max_length=255, null=True)),
                ('discord_id', models.BigIntegerField(blank=True, null=True)),
                ('discord_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EsiCourierEntityResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.evecourierentity')),
            ],
        ),
    ]
