# Generated by Django 4.1.5 on 2023-04-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_rename_response_esicourierentityresponse_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esicourierentityresponse',
            name='data',
            field=models.TextField(),
        ),
    ]
