# Generated by Django 4.1.5 on 2023-11-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_esicourierentityresponse_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('friendly_origin_name', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('friendly_destination_name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('wormhole', 'Wormhole')], default='standard', max_length=255)),
                ('small_price', models.FloatField(default=0)),
                ('medium_price', models.FloatField(default=0)),
                ('large_price', models.FloatField(default=0)),
            ],
        ),
    ]
