# Generated by Django 4.1.5 on 2023-12-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_freightroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightroute',
            name='no_collateral',
            field=models.BooleanField(default=False),
        ),
    ]
