# Generated by Django 4.1.5 on 2023-02-02 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_alter_evecharacterresourcelink_clicks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evecharacterresourcelink',
            name='clicks',
        ),
        migrations.CreateModel(
            name='EveCharacterResourceLinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.IntegerField()),
                ('ip', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referrals.evecharacterresourcelink')),
            ],
        ),
    ]
