# Generated by Django 4.1.5 on 2023-02-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_remove_evecharacterresourcelink_clicks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evecharacterresourcelinkclick',
            old_name='resource_id',
            new_name='resource_link',
        ),
    ]
