# Generated by Django 4.1.5 on 2023-03-06 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EsiCorporationContractResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.IntegerField()),
                ('corporation_id', models.IntegerField()),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EveContractEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.IntegerField()),
                ('entity_name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('character', 'Character'), ('corporation', 'Corporation')], max_length=32)),
                ('active', models.BooleanField(default=False)),
                ('contact_character_name', models.CharField(max_length=255)),
                ('contact_character_id', models.BigIntegerField()),
                ('contact_discord_name', models.CharField(max_length=255)),
                ('contact_discord_id', models.BigIntegerField()),
                ('ceo_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EveContractEntityReponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('size', models.IntegerField(choices=[(1, 'Scout'), (2, 'Small'), (3, 'Medium'), (4, 'Large'), (5, 'Open')])),
                ('fleet_fit', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts_v2.evecontractentity')),
            ],
        ),
    ]
