# Generated by Django 4.1.5 on 2023-03-06 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_v2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveContractEntityCodeChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.IntegerField()),
                ('challenge', models.CharField(max_length=36)),
            ],
        ),
        migrations.AlterField(
            model_name='evecontractentity',
            name='entity_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='EveContractEntityManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.IntegerField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts_v2.evecontractentity')),
            ],
        ),
    ]
