# Generated by Django 4.1.5 on 2023-03-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_v2', '0002_evecontractentitycodechallenge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evecontractentitycodechallenge',
            old_name='character_id',
            new_name='entity_id',
        ),
        migrations.AddField(
            model_name='evecontractentitycodechallenge',
            name='entity_name',
            field=models.CharField(default='Blank', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evecontractentitycodechallenge',
            name='type',
            field=models.CharField(choices=[('character', 'Character'), ('corporation', 'Corporation')], default='character', max_length=32),
            preserve_default=False,
        ),
    ]
