# Generated by Django 4.1.5 on 2023-03-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_v2', '0004_alter_evecontractentityreponsibility_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='evecontractentityreponsibility',
            name='ship_name',
            field=models.CharField(default='Breacher', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evecontractentityreponsibility',
            name='ship_type_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evecontractentityreponsibility',
            name='type',
            field=models.IntegerField(choices=[(1, '[NVY-1]'), (2, '[NVY-5]'), (3, '[NVY-30]')], default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='evecontractentityreponsibility',
            unique_together={('ship_name', 'type')},
        ),
        migrations.RemoveField(
            model_name='evecontractentityreponsibility',
            name='fleet_fit',
        ),
        migrations.RemoveField(
            model_name='evecontractentityreponsibility',
            name='title',
        ),
    ]
