# Generated by Django 4.1.5 on 2023-03-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_v2', '0005_evecontractentityreponsibility_ship_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsiEntityContractResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.IntegerField()),
                ('corporation_id', models.IntegerField(blank=True, null=True)),
                ('data', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='EsiCorporationContractResponse',
        ),
    ]
