# Generated by Django 4.1.5 on 2023-03-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_v2', '0009_delete_evecontractentityreponsibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='evecontractexpectation',
            name='legacy_alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
