# Generated by Django 4.1.5 on 2023-03-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_v2', '0010_evecontractexpectation_legacy_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evecontractexpectation',
            name='type',
            field=models.IntegerField(choices=[(1, '[NVY-1]'), (2, '[NVY-5]'), (3, '[NVY-30]'), (4, '[ADV-5]'), (5, '[ADV-30]'), (6, '[FL33T]')]),
        ),
    ]
