# Generated by Django 4.1.5 on 2023-03-24 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0005_evefitting_legacy_aliases'),
        ('contracts_v2', '0011_alter_evecontractexpectation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='evecontractexpectation',
            name='fitting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleets.evefitting'),
        ),
    ]
