# Generated by Django 4.1.5 on 2023-03-24 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0005_evefitting_legacy_aliases'),
        ('contracts_v2', '0012_evecontractexpectation_fitting'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evecontractexpectation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='evecontractexpectation',
            name='fitting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleets.evefitting'),
        ),
        migrations.RemoveField(
            model_name='evecontractexpectation',
            name='ship_name',
        ),
        migrations.RemoveField(
            model_name='evecontractexpectation',
            name='ship_type_id',
        ),
        migrations.RemoveField(
            model_name='evecontractexpectation',
            name='size',
        ),
        migrations.RemoveField(
            model_name='evecontractexpectation',
            name='type',
        ),
    ]
