# Generated by Django 4.1.5 on 2023-03-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_v2', '0013_alter_evecontractexpectation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveContractLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField(unique=True)),
                ('location_name', models.CharField(max_length=255)),
                ('friendly_location_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='evecontractexpectation',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='expectations', to='contracts_v2.evecontractlocation'),
        ),
    ]
