# Generated by Django 4.1.5 on 2023-03-25 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0005_evefitting_legacy_aliases'),
        ('contracts_v2', '0014_evecontractlocation_evecontractexpectation_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='evecontractexpectation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expectations', to='contracts_v2.evecontractlocation'),
        ),
        migrations.AlterUniqueTogether(
            name='evecontractexpectation',
            unique_together={('fitting', 'location')},
        ),
        migrations.RemoveField(
            model_name='evecontractexpectation',
            name='locations',
        ),
    ]
