# Generated by Django 4.1.5 on 2023-03-25 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_v2', '0016_evecontracttaxreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evecontracttaxreport',
            name='end_range',
            field=models.DateField(default=datetime.datetime(2023, 3, 25, 23, 23, 42, 843027, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='evecontracttaxreport',
            name='start_range',
            field=models.DateField(default=datetime.datetime(2023, 2, 23, 23, 23, 42, 842922, tzinfo=datetime.timezone.utc)),
        ),
    ]
