# Generated by Django 4.1.5 on 2023-03-26 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_v2', '0017_alter_evecontracttaxreport_end_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evecontractexpectation',
            name='aliases',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evecontracttaxreport',
            name='end_range',
            field=models.DateField(default=datetime.datetime(2023, 3, 26, 1, 7, 5, 996662, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='evecontracttaxreport',
            name='start_range',
            field=models.DateField(default=datetime.datetime(2023, 2, 24, 1, 7, 5, 996556, tzinfo=datetime.timezone.utc)),
        ),
    ]
