# Generated by Django 4.1.5 on 2023-03-26 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_v2', '0018_evecontractexpectation_aliases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evecontracttaxreport',
            name='end_range',
            field=models.DateField(default=datetime.datetime(2023, 3, 26, 1, 9, 10, 413776, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='evecontracttaxreport',
            name='start_range',
            field=models.DateField(default=datetime.datetime(2023, 2, 24, 1, 9, 10, 413672, tzinfo=datetime.timezone.utc)),
        ),
    ]
