# Generated by Django 4.1.5 on 2023-03-26 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_v2', '0021_alter_evecontracttaxreport_end_range_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evecontractexpectation',
            unique_together=set(),
        ),
    ]
