# Generated by Django 4.1.5 on 2023-03-26 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0005_evefitting_legacy_aliases'),
        ('contracts_v2', '0022_alter_evecontractexpectation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evecontractexpectation',
            name='fitting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleets.evefitting'),
        ),
        migrations.AlterUniqueTogether(
            name='evecontractexpectation',
            unique_together={('fitting', 'location')},
        ),
    ]
