# Generated by Django 4.1.5 on 2023-03-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_v2', '0023_alter_evecontractexpectation_fitting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esientitycontractresponse',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
