# Generated by Django 4.1.5 on 2023-03-30 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_v2', '0024_esientitycontractresponse_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='esientitycontractresponse',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts_v2.evecontractentity'),
        ),
    ]
