# Generated by Django 4.1.5 on 2023-03-30 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_v2', '0025_esientitycontractresponse_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esientitycontractresponse',
            name='character_id',
        ),
        migrations.RemoveField(
            model_name='esientitycontractresponse',
            name='corporation_id',
        ),
    ]
