# Generated by Django 4.1.5 on 2023-06-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_v2', '0026_remove_esientitycontractresponse_character_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evecontractentity',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
