# Generated by Django 4.1.5 on 2023-06-29 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_v2", "0028_evecontractentity_domain_evedoctrineexpectation"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_id", models.BigIntegerField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("outstanding", "Outstanding"),
                            ("completed", "Completed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=32)),
                ("assignee_id", models.IntegerField(blank=True, null=True)),
                ("acceptor_id", models.IntegerField(blank=True, null=True)),
                ("issuer_external_id", models.IntegerField()),
                (
                    "issuer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contracts_v2.evecontractentity",
                    ),
                ),
            ],
        ),
    ]
