# Generated by Django 4.1.5 on 2023-06-29 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fleets", "0012_evedoctrine_primary"),
        ("contracts_v2", "0029_evecontract"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecontract",
            name="fitting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fleets.evefitting",
            ),
        ),
    ]
