# Generated by Django 4.1.5 on 2023-07-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts_v2", "0030_evecontract_fitting"),
    ]

    operations = [
        migrations.AddField(
            model_name="evecontractlocation",
            name="primary",
            field=models.BooleanField(default=False),
        ),
    ]
