# Generated by Django 4.1.5 on 2023-07-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts_v2', '0031_evecontractlocation_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evecontractentity',
            name='active',
        ),
    ]
