# Generated by Django 4.1.5 on 2023-04-02 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EveRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporation_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=255)),
                ('member_count', models.IntegerField()),
                ('alliance_id', models.IntegerField()),
                ('faction_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EveRosterMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('character_id', models.IntegerField()),
                ('monthly_kills', models.IntegerField()),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='rosters.everoster')),
            ],
        ),
    ]
