# Generated by Django 4.1.5 on 2023-04-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='everoster',
            name='ceo_id',
            field=models.IntegerField(default=634915984),
            preserve_default=False,
        ),
    ]
