# Generated by Django 4.1.5 on 2023-06-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosters', '0002_everoster_ceo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='everoster',
            name='alliance_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='everoster',
            name='ceo_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='everoster',
            name='faction_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='everoster',
            name='member_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='everoster',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='everoster',
            name='ticker',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
