# Generated by Django 4.1.5 on 2024-01-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rosters", "0004_everostermember_monthly_fleets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="everostermember",
            name="main_character_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="everostermember",
            name="main_character_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
