# Generated by Django 4.1.5 on 2023-03-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EveFitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ship_name', models.CharField(max_length=255)),
                ('ship_type_id', models.IntegerField()),
                ('eft_format', models.TextField()),
                ('multibuy_format', models.TextField()),
                ('latest_price', models.DecimalField(decimal_places=2, max_digits=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('build_updated', models.BooleanField(default=False)),
                ('fl33t_updated', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EveFleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_id', models.IntegerField()),
                ('motd', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EveDoctrine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fittings', models.ManyToManyField(blank=True, null=True, to='fleets.evefitting')),
            ],
        ),
    ]
