# Generated by Django 4.1.5 on 2023-03-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0002_evefitting_latest_version_alter_evedoctrine_fittings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evefitting',
            name='multibuy_format',
            field=models.TextField(blank=True, null=True),
        ),
    ]
