# Generated by Django 4.1.5 on 2023-03-22 18:14

from django.db import migrations, models
import django_extensions.db.fields
from ..models import EveDoctrine, EveFitting

def generate_slugs_for(model):
    for instance in model.objects.all().only('name'):
        instance.save(update_fields=['slug'])

def generate_slugs(apps, schema_editor):
    generate_slugs_for(EveDoctrine)
    generate_slugs_for(EveFitting)

class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0003_alter_evefitting_multibuy_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name="evedoctrine",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="evefitting",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='evedoctrine',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name'),
        ),
        migrations.AddField(
            model_name='evefitting',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name'),
        ),
        migrations.RunPython(
            generate_slugs,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='evedoctrine',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='evefitting',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
