# Generated by Django 4.1.5 on 2023-03-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0004_evedoctrine_slug_evefitting_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='evefitting',
            name='legacy_aliases',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
