# Generated by Django 4.1.5 on 2023-04-06 19:19

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0007_evedoctrine_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='evedoctrinetag',
            name='text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
