# Generated by Django 4.1.5 on 2023-04-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0008_evedoctrinetag_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='evedoctrine',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
