# Generated by Django 4.1.5 on 2023-06-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0009_evedoctrine_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='evedoctrine',
            name='universal',
            field=models.BooleanField(default=False),
        ),
    ]
