# Generated by Django 4.1.5 on 2023-06-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0010_evedoctrine_universal'),
    ]

    operations = [
        migrations.AddField(
            model_name='evedoctrine',
            name='composition',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
