# Generated by Django 4.1.5 on 2023-07-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0013_remove_evefleet_motd_evefleet_audience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evefleet',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
