# Generated by Django 4.1.5 on 2023-07-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0014_alter_evefleet_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evefleet',
            name='fleet_commander_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evefleet',
            name='fleet_commander_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evefleet',
            name='fleet_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
