# Generated by Django 4.0.10 on 2023-07-10 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0017_evefleetdiscordwebhook_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsiFleet',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_free_move', models.BooleanField(default=False)),
                ('is_registered', models.BooleanField(default=False)),
                ('is_voice_enabled', models.BooleanField(default=False)),
                ('motd', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='evefleet',
            name='type',
            field=models.CharField(choices=[('frontline', 'Frontline'), ('structure', 'Structure'), ('stratop', 'Strategic Operation'), ('training', 'Training'), ('roam', 'Roam')], default='frontline', max_length=255),
        ),
        migrations.CreateModel(
            name='EsiFleetMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.IntegerField()),
                ('join_time', models.DateTimeField()),
                ('role', models.CharField(max_length=255)),
                ('role_name', models.CharField(max_length=255)),
                ('ship_type_id', models.IntegerField()),
                ('solar_system_id', models.IntegerField()),
                ('squad_id', models.IntegerField()),
                ('station_id', models.IntegerField()),
                ('takes_fleet_warp', models.BooleanField(default=False)),
                ('wing_id', models.IntegerField()),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleets.esifleet')),
            ],
        ),
        migrations.AddField(
            model_name='esifleet',
            name='fleet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleets.evefleet'),
        ),
    ]
