# Generated by Django 4.1.5 on 2023-07-10 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0018_esifleet_alter_evefleet_type_esifleetmember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esifleet',
            name='fleet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleets.evefleet'),
        ),
    ]
