# Generated by Django 4.1.5 on 2023-07-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0019_alter_esifleet_fleet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esifleetmember',
            name='station_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
