# Generated by Django 4.1.5 on 2023-07-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0020_alter_esifleetmember_station_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='esifleetmember',
            name='character_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='esifleetmember',
            name='ship_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='esifleetmember',
            name='solar_system_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
