# Generated by Django 4.1.5 on 2023-07-10 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0021_esifleetmember_character_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsiFleetMemberTrackingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ship_type_id', models.IntegerField()),
                ('solar_system_id', models.IntegerField()),
                ('station_id', models.IntegerField(blank=True, null=True)),
                ('ship_name', models.CharField(blank=True, max_length=255, null=True)),
                ('solar_system_name', models.CharField(blank=True, max_length=255, null=True)),
                ('esi_fleet_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleets.esifleetmember')),
            ],
        ),
    ]
