# Generated by Django 4.1.5 on 2023-07-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0022_esifleetmembertrackinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='esifleet',
            name='external_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='esifleet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
