# Generated by Django 4.1.5 on 2023-07-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0023_esifleet_external_id_alter_esifleet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esifleet',
            name='external_id',
        ),
        migrations.AlterField(
            model_name='esifleet',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
