# Generated by Django 4.1.5 on 2023-07-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0024_remove_esifleet_external_id_alter_esifleet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveFleetMOTDTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('frontline', 'Frontline'), ('structure', 'Structure'), ('stratop', 'Strategic Operation'), ('training', 'Training'), ('roam', 'Roam')], max_length=255)),
                ('audience', models.CharField(choices=[('militia', 'Militia'), ('alliance', 'Alliance'), ('academy', 'Academy')], max_length=255)),
                ('motd', models.TextField()),
            ],
        ),
    ]
