# Generated by Django 4.1.5 on 2023-07-10 09:47

from django.db import migrations, models
from fleets.helpers import type_id_to_group_name

def set_ship_type_name(apps, schema_editor):
    EveFitting = apps.get_model('fleets', 'EveFitting')
    for eve_fitting in EveFitting.objects.all():
        eve_fitting.ship_type_name = type_id_to_group_name(eve_fitting.ship_type_id)
        eve_fitting.save()


class Migration(migrations.Migration):
    dependencies = [
        ("fleets", "0025_evefleetmotdtemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="evefitting",
            name="ship_type_name",
            field=models.CharField(null=True, max_length=255),
        ),
        migrations.RunPython(set_ship_type_name),
        migrations.AlterField(
            model_name="evefitting",
            name="ship_type_name",
            field=models.CharField(max_length=255),
        )
    ]
