# Generated by Django 4.0.10 on 2023-07-11 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0026_alter_esifleetmember_character_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='esifleetmember',
            unique_together={('fleet', 'character_id')},
        ),
    ]
