# Generated by Django 4.1.5 on 2023-07-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0026_evefitting_ship_type_name'),
        ('fleets', '0027_alter_esifleetmember_unique_together'),
    ]

    operations = [
    ]
