# Generated by Django 4.1.5 on 2023-10-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0031_evefleetdiscordwebhook_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evefleet',
            name='type',
            field=models.CharField(choices=[('frontline', 'Frontline'), ('battlefield', 'Battlefield'), ('stratop', 'Strategic'), ('training', 'Training')], default='frontline', max_length=255),
        ),
        migrations.AlterField(
            model_name='evefleetmotdtemplate',
            name='type',
            field=models.CharField(choices=[('frontline', 'Frontline'), ('battlefield', 'Battlefield'), ('stratop', 'Strategic'), ('training', 'Training')], max_length=255),
        ),
    ]
