# Generated by Django 4.1.5 on 2023-11-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0032_alter_evefleet_type_alter_evefleetmotdtemplate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evefleet',
            name='audience',
            field=models.CharField(choices=[('militia', 'Militia'), ('alliance', 'Alliance'), ('all', 'All')], default='militia', max_length=255),
        ),
        migrations.AlterField(
            model_name='evefleet',
            name='type',
            field=models.CharField(choices=[('stratop', 'Strategic'), ('flash_form', 'Flash Form'), ('frontline', 'Frontline'), ('battlefield', 'Battlefield'), ('fun_fleet', 'Fun Fleet'), ('random', 'Random'), ('training', 'Training')], default='frontline', max_length=255),
        ),
        migrations.AlterField(
            model_name='evefleetdiscordwebhook',
            name='audience',
            field=models.CharField(choices=[('militia', 'Militia'), ('alliance', 'Alliance'), ('all', 'All')], max_length=255),
        ),
        migrations.AlterField(
            model_name='evefleetmotdtemplate',
            name='audience',
            field=models.CharField(choices=[('militia', 'Militia'), ('alliance', 'Alliance'), ('all', 'All')], max_length=255),
        ),
        migrations.AlterField(
            model_name='evefleetmotdtemplate',
            name='type',
            field=models.CharField(choices=[('stratop', 'Strategic'), ('flash_form', 'Flash Form'), ('frontline', 'Frontline'), ('battlefield', 'Battlefield'), ('fun_fleet', 'Fun Fleet'), ('random', 'Random'), ('training', 'Training')], max_length=255),
        ),
    ]
