# Generated by Django 4.1.5 on 2023-11-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleets', '0033_alter_evefleet_audience_alter_evefleet_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evefleet',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='evefleet',
            name='audience',
            field=models.CharField(choices=[('alliance', 'Alliance'), ('militia', 'Militia'), ('alliance_high_priority', 'Alliance (alarm clock)')], default='alliance', max_length=255),
        ),
        migrations.AlterField(
            model_name='evefleet',
            name='type',
            field=models.CharField(choices=[('stratop', 'Strategic'), ('flash_form', 'Flash Form'), ('frontline', 'Frontline'), ('battlefield', 'Battlefield'), ('fun_fleet', 'Fun Fleet'), ('training', 'Training')], default='fun_fleet', max_length=255),
        ),
        migrations.AlterField(
            model_name='evefleetdiscordwebhook',
            name='audience',
            field=models.CharField(choices=[('alliance', 'Alliance'), ('militia', 'Militia'), ('alliance_high_priority', 'Alliance (alarm clock)')], max_length=255),
        ),
        migrations.AlterField(
            model_name='evefleetmotdtemplate',
            name='audience',
            field=models.CharField(choices=[('alliance', 'Alliance'), ('militia', 'Militia'), ('alliance_high_priority', 'Alliance (alarm clock)')], max_length=255),
        ),
        migrations.AlterField(
            model_name='evefleetmotdtemplate',
            name='type',
            field=models.CharField(choices=[('stratop', 'Strategic'), ('flash_form', 'Flash Form'), ('frontline', 'Frontline'), ('battlefield', 'Battlefield'), ('fun_fleet', 'Fun Fleet'), ('training', 'Training')], max_length=255),
        ),
    ]
