# Generated by Django 4.1.5 on 2023-02-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreightRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('friendly_origin_name', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('friendly_destination_name', models.CharField(max_length=255)),
                ('isotopes', models.IntegerField()),
            ],
        ),
    ]
