# Generated by Django 4.1.5 on 2023-02-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightroute',
            name='midpoints',
            field=models.IntegerField(default=1),
        ),
    ]
