# Generated by Django 4.1.5 on 2023-06-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0003_freightroute_isk_jump_freightroute_isk_m3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightroute',
            name='low_risk',
            field=models.BooleanField(default=False),
        ),
    ]
