# Generated by Django 4.1.5 on 2023-06-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0004_freightroute_low_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightroute',
            name='jump_freight_required',
            field=models.BooleanField(default=False),
        ),
    ]
