# Generated by Django 4.1.5 on 2023-06-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0005_freightroute_jump_freight_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightroute',
            name='jump_freight_only',
            field=models.BooleanField(default=False),
        ),
    ]
